version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8.11.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests with coverage
          command: yarn test --coverage

      - run:
          name: Create Production Build
          command: yarn build

      - run:
          name: Deploy on Netlify
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              wget https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz
              tar -xzvf netlifyctl-linux-amd64-0.4.0.tar.gz
              ./netlifyctl version
              ./netlifyctl deploy -y -s $NETLIFY_SITE_ID -A $NETLIFY_TOKEN -P ./build/
            fi

      - run:
          name: Upload coverage report to Codecov
          command: ./node_modules/codecov/bin.codecov