version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:8.11.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Create Production Build
          command: yarn build

      - run:
          name: Deploy on Netlify
          command: |
            wget https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz
            tar -xzvf netlifyctl-linux-amd64-0.4.0.tar.gz
            ./netlifyctl version
            ./netlifyctl deploy -y -s $NETLIFY_SITE_ID -A $NETLIFY_TOKEN -b ./build/